// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD__Jlzd3p-XL5Pzka6CpncnsfS9B7ZoC0',
    appId: '1:27844000438:web:b5c865ca4a69900c66c417',
    messagingSenderId: '27844000438',
    projectId: 'hedieaty-app-8e79c',
    authDomain: 'hedieaty-app-8e79c.firebaseapp.com',
    storageBucket: 'hedieaty-app-8e79c.firebasestorage.app',
    measurementId: 'G-9W5BYDBN50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0h8L5mUthme88r-CyhmqMjVn2MRcuvqs',
    appId: '1:27844000438:android:dfd537cba7099b8266c417',
    messagingSenderId: '27844000438',
    projectId: 'hedieaty-app-8e79c',
    storageBucket: 'hedieaty-app-8e79c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD__Jlzd3p-XL5Pzka6CpncnsfS9B7ZoC0',
    appId: '1:27844000438:web:d4c46f8f61dff5c866c417',
    messagingSenderId: '27844000438',
    projectId: 'hedieaty-app-8e79c',
    authDomain: 'hedieaty-app-8e79c.firebaseapp.com',
    storageBucket: 'hedieaty-app-8e79c.firebasestorage.app',
    measurementId: 'G-GHRS7FT9LQ',
  );
}
